import assert from 'node:assert';
import crypto from 'node:crypto';
import { supabaseDb } from './lib/db.mjs';
const calls = []; let next = { status: 200, body: [] };
const f = async (url, o) => { calls.push({ url, o }); const n = next; return { ok: n.status < 300, status: n.status, text: async () => JSON.stringify(n.body) }; };
let db = supabaseDb({ url: 'https://x.supabase.co/', key: 'sb_secret_abc', fetchImpl: f });
await db.listBookings({ since: 5 });
assert.equal(calls[0].url, 'https://x.supabase.co/rest/v1/bookings?select=*&order=updated_at.asc&limit=5000&updated_at=gt.5');
assert.equal(calls[0].o.headers.apikey, 'sb_secret_abc'); assert(!calls[0].o.headers.Authorization, 'new key: apikey only');
db = supabaseDb({ url: 'https://x.supabase.co', key: 'eyJhbGciOi.legacy', fetchImpl: f });
next = { status: 200, body: [{ id: 'A', date: '2026-10-06', start: 600, dur: 30, barber_id: 'b1', status: 'inprogress', data: { name: 'n', phone: '081' }, updated_at: '7' }] };
const r = await db.updateBooking({ id: 'A', date: '2026-10-06', start: 600, dur: 30, barberId: 'b1', status: 'inprogress', phone: '081', updatedAt: 7 }, { expectStatus: 'confirmed', notNotified: 'due' });
const c = calls[calls.length - 1];
assert.equal(c.o.method, 'PATCH'); assert.equal(c.o.headers.Authorization, 'Bearer eyJhbGciOi.legacy');
assert.equal(c.url, 'https://x.supabase.co/rest/v1/bookings?id=eq.A&status=eq.confirmed&data->notified->>due=is.null');
assert.equal(JSON.parse(c.o.body).phone_key, '081'); assert.equal(r.barberId, 'b1'); assert.equal(r.updatedAt, 7); assert.equal(r.phone, '081');
next = { status: 200, body: [] }; assert.equal(await db.updateBooking({ id: 'A' }, { expectStatus: 'confirmed' }), null, 'no match -> null');
next = { status: 409, body: { code: '23P01', message: 'conflicting key value violates exclusion constraint' } };
assert.deepEqual(await db.insertBooking({ id: 'B' }), { ok: false, overlap: true });
next = { status: 409, body: { code: '23505', message: 'duplicate key' } };
assert.deepEqual(await db.insertBooking({ id: 'B' }), { ok: false, duplicate: true });
next = { status: 200, body: [{ staff_id: 'b1', name: 'ช่างเอ', role: 'barber' }] };
assert.equal((await db.claimLinkCode('123456', 'U1')).staffId, 'b1');
assert(calls[calls.length - 1].url.endsWith('staff?link_code=eq.123456'));
next = { status: 200, body: {} };
const u = await db.uploadSlip(Buffer.from('x'), 'image/jpeg', 'BK1-u.jpg');
assert.equal(u, 'https://x.supabase.co/storage/v1/object/public/slips/BK1-u.jpg');
console.log('db adapter: all request shapes OK');

// endpoint files load and behave without a database
process.env.STAFF_KEY = 'SK'; process.env.LINE_CHANNEL_SECRET = 'cs'; process.env.CRON_SECRET = 'cr';
const app = (await import('./api/app.mjs')).default, line = (await import('./api/line.mjs')).default, tick = (await import('./api/tick.mjs')).default;
let res = await app.fetch(new Request('https://h/api/app?a=health')); let j = await res.json();
assert(j.ok && j.db.configured === false && j.line.secret === true, 'health without db');
res = await app.fetch(new Request('https://h/api/app', { method: 'POST', body: JSON.stringify({ a: 'create', booking: { id: 'X', date: '2026-10-06', start: 600, dur: 30, barberId: 'b1', name: 'n' } }) }));
j = await res.json(); assert(res.status === 503 && /SUPABASE_URL/.test(j.error), 'clear error when db missing');
res = await app.fetch(new Request('https://h/api/app', { method: 'OPTIONS' })); assert.equal(res.status, 204); assert.equal(res.headers.get('access-control-allow-origin'), '*');
const body = JSON.stringify({ events: [] });
res = await line.fetch(new Request('https://h/api/line', { method: 'POST', body, headers: { 'x-line-signature': 'bad' } })); assert.equal(res.status, 401);
res = await line.fetch(new Request('https://h/api/line', { method: 'POST', body, headers: { 'x-line-signature': crypto.createHmac('sha256', 'cs').update(body).digest('base64') } })); assert.equal(res.status, 200, 'LINE verify (empty events) passes');
res = await tick.fetch(new Request('https://h/api/tick')); assert.equal(res.status, 401);
console.log('endpoints: OK');
